### ISSUE TITLE
ChainedModelChoiceField.choices initialization incompatibility with Django 5.0

### ISSUE THREAD

**Issue by Dmitri-Sintsov** [digi604/django-smart-selects#353]
## Checklist

- [x] This issue is not about installing previous versions of django-smart-selects older than 1.2.8. I understand that previous versions are insecure and will not receive any support whatsoever.
- [x] I have verified that that issue exists against the `master` branch of django-smart-selects.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have debugged the issue to the `smart_selects` app.
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included all relevant sections of `models.py`, `forms.py`, and `views.py` with problems.
- [x] I have used [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to style all of my posted code.

## Steps to reproduce

The following error is being produced while the initialization of Django 5.0 project:

```
 File "/home/user/work/ispdevenv/lib/python3.10/site-packages/smart_selects/db_fields.py", line 8, in <module>
    from smart_selects import form_fields
  File "/home/user/work/ispdevenv/lib/python3.10/site-packages/smart_selects/form_fields.py", line 10, in <module>
    class ChainedModelChoiceField(ModelChoiceField):
  File "/home/user/work/ispdevenv/lib/python3.10/site-packages/smart_selects/form_fields.py", line 62, in ChainedModelChoiceField
    choices = property(_get_choices, ChoiceField._set_choices)
AttributeError: type object 'ChoiceField' has no attribute '_set_choices'
```

## Actual behavior

Impossible to initialize `ChainedModelChoiceField.choices`.

## Expected behavior

Used to work fine with Django<5.0

See https://github.com/django/django/commit/500e01073adda32d5149624ee9a5cb7aa3d3583f for the reference.

**Comment by djruesch** [comment]
Anyone have an ETA when this will be fixed for Django 5.0+

**Comment by lguariento** [comment]
Hello, same issue here. Is there a temporary workaround at least?

**Comment by lguariento** [comment]
I have renamed `ChoiceField._set_choices` into `ChoiceField.choices`. That did the trick!

**Comment by rickylenon** [comment]
> I have renamed `ChoiceField._set_choices` into `ChoiceField.choices`. That did the trick!

This works with me. But i get error:
bool' object has no attribute 'startswith'

My workaround is to change something under class JqueryMediaMixin
line 50:
...
media += Media(js=js)
return media
        
replace with:
#  make sure js is string type
if isinstance(js, str):
    media += Media(js=js)
return media
 
 now it works!
 
 PS:
File to edit:
..site-packages/smart_selects/widgets.py

**Comment by yardensachs** [comment]
its fixed in 1.7.1, but its not in pypi

**Comment by Sinanaltundag** [comment]
> its fixed in 1.7.1, but v1.7.1 is not in pypi, you need to install from github

I install 1.7.1 from github but it have problem on django admin

Django Version: | 5.0.6
NoReverseMatch
Reverse for 'chained_filter' not found. 'chained_filter' is not a valid view function or pattern name.
C:\...\Lib\site-packages\django\urls\resolvers.py, line 851, in _reverse_with_prefix
django.contrib.admin.options.change_view
C:\...\Scripts\python.exe
3.11.3

**Comment by lguariento** [comment]
Have you had a look at [this](https://stackoverflow.com/questions/65085770/reverse-for-chained-filter-not-found-chained-filter-is-not-a-valid-view-fun)?

**Comment by aijazmahdavi** [comment]
> I have renamed `ChoiceField._set_choices` into `ChoiceField.choices`. That did the trick!

this has an issue, if we are working on local and live then u need to edit files in env which is not recommended

**Comment by lguariento** [comment]
Of course, it's just a temporary workaround. Hopefully it'll officially fixed soon.

**Comment by hernansaa** [comment]
@lguariento @Sinanaltundag you guys just have fixed all my problems. thanks a lot!
