### ISSUE TITLE
Help getting the app to work on 1.8

### ISSUE THREAD

**Issue by tkovalsky** [digi604/django-smart-selects#101]
Hi - could you help me with this wall i hit while trying to implement the app into my project?

https://github.com/trecweb

In summary, the multi-select is not working as expected

Thanks

**Comment by jimmykobe1171** [comment]
Hi, what's the problem? Do you mean django 1.8 ?

**Comment by toweralaka** [comment]
Hi! I also cant get it to work on DJANGO 1.9 
ImportError: cannot import name 'ChainedForeignKey'

**Comment by blag** [comment]
This should be fixed in #141. If this is still an issue, please give more troubleshooting information. Closing.
